name: Deploy to Azure Container Instance

on:
  push:
    paths:
      - 'app/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        run: |
          sudo apt-get install curl
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version --output table

      - name: Log in to Azure Container Registry
        run: |
          az login --service-principal --username ${{ secrets.SP_USERNAME }} --password ${{ secrets.SP_PASSWORD }} --tenant ${{ secrets.SP_TENANT }}
          az acr login --name openairegadm.azurecr.io

      - name: Build and push Docker image
        run: |
          docker build -t openairegadm.azurecr.io/quickstart:v1 ./app
          docker push openairegadm.azurecr.io/quickstart:v1

      - name: Deploy to Azure Container Instance
        run: |
          az container create \
          --resource-group openai_quickstart \
          --name quickstart \
          --image openairegadm.azurecr.io/quickstart \
          --registry-login-server openairegadm.azurecr.io \
          --registry-username ${{ secrets.SP_USERNAME }} \
          --registry-password ${{ secrets.SP_PASSWORD }} \
          --dns-name-label alexmaccalmanopenaiquickstart \
          --ports 5000 \
          --memory 1.5

         